from app.core.fault_tolerance import ollama_breaker
from app.domain.models.state import PlatformState
from app.infrastructure.llm.ollama import get_chat_model
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

@ollama_breaker
async def generator_node(state: PlatformState) -> dict:
    """
    Synthesizes the finalized contextual fragments generated by the agents into a
    cohesive downstream answer.
    """
    context = state.get("compressed_context", "")
    query = state.get("rewritten_query", state.get("original_query", ""))
    feedback = state.get("reflection_feedback", "")

    # feedback_section is substituted as a template VARIABLE (not string-concatenated
    # into the template itself) because reflection_node's critique text often quotes
    # retrieved context verbatim - including things like the DAG's literal Python dict
    # syntax `{'owner': 'data-engineering', ...}`. Baking that into the template string
    # made ChatPromptTemplate try to re-parse those braces as its own placeholders and
    # crash. Passing it as a value means it's inserted literally, never re-parsed.
    system_prompt = (
        "You are an AI Data Intelligence assistant. Answer the user's query using ONLY facts "
        "stated in the provided context.\n"
        "- Re-read the full context before answering. If the query asks for a specific fact - a "
        "number, date, name, or value - your answer MUST state that exact fact; do not substitute "
        "a nearby description or paraphrase in its place.\n"
        "- Search the ENTIRE context, not just the first matching passage, before concluding "
        "something is missing - relevant details are sometimes in a later paragraph or a "
        "different chunk than where the topic is first mentioned.\n"
        "- Address exactly what was asked, directly and concisely. Lead with the answer itself, "
        "then add only as much supporting detail as the query calls for.\n"
        "- Do not pad the response with unrelated context, other retrieved snippets, or generic "
        "caveats that were not asked for.\n"
        "- Only after checking the entire context: if it partially answers the query, give the "
        "part it does answer, then state plainly what is missing - do not guess or speculate to "
        "fill the gap. If it does not answer the query at all, say so directly instead of "
        "inventing an answer."
        "{feedback_section}"
    )
    feedback_section = (
        f"\nCRITICAL INSTRUCTION: Re-evaluate your previous generated attempt based on this "
        f"exact evaluation feedback: {feedback}"
        if feedback else ""
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "Available Context: {context}\n\nQuery: {query}")
    ])

    # Low temperature: this is factual extraction over a small knowledge base, where
    # precisely quoting the right fact matters far more than varied prose. Higher
    # temperatures were observed to make the model substitute a nearby but wrong
    # clause for the actually-requested fact (e.g. answering "Word2Vec introduced
    # dense vectors" while dropping the year that was actually asked for).
    llm = get_chat_model(temperature=0.1)
    chain = prompt | llm | StrOutputParser()

    final_output = await chain.ainvoke({
        "context": context,
        "query": query,
        "feedback_section": feedback_section,
    })

    return {"answer": final_output}
