from app.domain.models.state import PlatformState
from app.infrastructure.llm.ollama import get_chat_model
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

def generator_node(state: PlatformState) -> dict:
    """
    Synthesizes the finalized contextual fragments generated by the agents into a 
    cohesive downstream answer.
    """
    context = state.get("compressed_context", "")
    query = state.get("rewritten_query", state.get("original_query", ""))
    feedback = state.get("reflection_feedback", "")
    
    system_prompt = "You are an AI Data Intelligence assistant. Answer the user query using ONLY the provided context."
    if feedback:
        system_prompt += f"\nCRITICAL INSTRUCTION: Re-evaluate your previous generated attempt based on this exact evaluation feedback: {feedback}"
        
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "Available Context: {context}\n\nQuery: {query}")
    ])
    
    # Increased temperature slightly for smooth generation prose
    llm = get_chat_model(temperature=0.3)
    chain = prompt | llm | StrOutputParser()
    
    final_output = chain.invoke({"context": context, "query": query})
    
    return {"answer": final_output}
